version: '2'
services:
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: fifa-stats
      POSTGRES_USER: fifa-stats
      POSTGRES_DB: fifa-stats
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
